<def f='include/boost/exception/exception.hpp' l='212' type='void boost::exception::exception()'/>
