<def f='include/boost/thread/exceptions.hpp' l='54' type='void boost::thread_exception::thread_exception(int ev, const std::string &amp; what_arg)'/>
<use f='include/boost/thread/exceptions.hpp' l='112' u='c' c='_ZN5boost10lock_errorC1EiRKSs'/>
<use f='include/boost/thread/exceptions.hpp' l='139' u='c' c='_ZN5boost21thread_resource_errorC1EiRKSs'/>
<use f='include/boost/thread/exceptions.hpp' l='167' u='c' c='_ZN5boost25unsupported_thread_optionC1EiRKSs'/>
<use f='include/boost/thread/exceptions.hpp' l='191' u='c' c='_ZN5boost23invalid_thread_argumentC1EiRKSs'/>
<use f='include/boost/thread/exceptions.hpp' l='215' u='c' c='_ZN5boost23thread_permission_errorC1EiRKSs'/>
