<inh f='include/boost/system/system_error.hpp' l='47' c='_ZN5boost6system12system_errorD1Ev'/>
<def f='include/boost/thread/exceptions.hpp' l='59' type='void boost::thread_exception::~thread_exception()'/>
<ovr f='include/boost/thread/exceptions.hpp' l='116' c='_ZN5boost10lock_errorD1Ev'/>
<ovr f='include/boost/thread/exceptions.hpp' l='144' c='_ZN5boost21thread_resource_errorD1Ev'/>
