<def f='include/boost/iostreams/detail/error.hpp' l='31' type='std::ios::failure boost::iostreams::detail::bad_putback()'/>
<use f='include/boost/iostreams/detail/streambuf/direct_streambuf.hpp' l='166' u='c' c='_ZN5boost9iostreams6detail16direct_streambuf9pbackfailENT0_8int_typeE'/>
<use f='include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp' l='279' u='c' c='_ZN5boost9iostreams6detail18indirect_streambuf9pbackfailENT0_8int_typeE'/>
