<inh f='include/boost/thread/exceptions.hpp' l='59' c='_ZN5boost16thread_exceptionD1Ev'/>
<def f='include/boost/thread/exceptions.hpp' l='144' type='void boost::thread_resource_error::~thread_resource_error()'/>
