<def f='include/boost/throw_exception.hpp' l='82' type='void boost::exception_detail::throw_exception_(const E &amp; x, const char * current_function, const char * file, int line)'/>
