<inh f='include/boost/thread/exceptions.hpp' l='59' c='_ZN5boost16thread_exceptionD1Ev'/>
<def f='include/boost/thread/exceptions.hpp' l='116' type='void boost::lock_error::~lock_error()'/>
