<def f='include/boost/date_time/constrained_value.hpp' l='91' type='std::out_of_range boost::CV::simple_exception_policy::exception_wrapper::operator out_of_range() const'/>
<doc f='include/boost/date_time/constrained_value.hpp' l='87'>// In order to support throw_exception mechanism in the BOOST_NO_EXCEPTIONS mode,
      // we&apos;ll have to provide a way to acquire std::exception from the exception being thrown.
      // However, we cannot derive from it, since it would make it interceptable by this class,
      // which might not be what the user wanted.</doc>
