<dec f='include/c++/4.9/stdexcept' l='121' type='void std::runtime_error::~runtime_error()'/>
<ovr f='include/boost/system/system_error.hpp' l='47' c='_ZN5boost6system12system_errorD1Ev'/>
<ovr f='include/boost/property_tree/detail/exception_implementation.hpp' l='38' c='_ZN5boost13property_tree11ptree_errorD1Ev'/>
