<def f='include/c++/4.9/future' l='1026' type='void std::promise::set_exception(std::__exception_ptr::exception_ptr __p)'/>
